--- #YAML:1.0
name:                Devel-XRay
version:             0.941
abstract:            See What a Perl Module Is Doing
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Carp:                          0
    Filter::Simple:                0.78
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jeff Bisbee <jbisbee@cpan.org>
