# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-XRay
version:      0.92
version_from: lib/Devel/XRay.pm
installdirs:  site
requires:
    Carp:                          0
    Filter::Simple:                0.78
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
